// const data = [
//   [
//     {
//       name: 'Backquote',
//       addClass: 'Backquote',
//       caseCapsEng: '`',
//       caseCapsShiftEng: '~',
//       caseDownEng: '`',
//       caseUpEng: '~',
//       caseCapsUkr: "'",
//       caseCapsShiftUkr: '₴',
//       caseDownUkr: "'",
//       caseUpUkr: '₴',
//     },
//     {
//       name: 'Digit1',
//       addClass: 'Digit1',
//       caseCapsEng: '1',
//       caseCapsShiftEng: '!',
//       caseDownEng: '1',
//       caseUpEng: '!',
//       caseCapsUkr: '1',
//       caseCapsShiftUkr: '!',
//       caseDownUkr: '1',
//       caseUpUkr: '!',
//     },
//     {
//       name: 'Digit2',
//       addClass: 'Digit2',
//       caseCapsEng: '2',
//       caseCapsShiftEng: '@',
//       caseDownEng: '2',
//       caseUpEng: '@',
//       caseCapsUkr: '2',
//       caseCapsShiftUkr: '"',
//       caseDownUkr: '2',
//       caseUpUkr: '"',
//     },
//     {
//       name: 'Digit3',
//       addClass: 'Digit3',
//       caseCapsEng: '3',
//       caseCapsShiftEng: '#',
//       caseDownEng: '3',
//       caseUpEng: '#',
//       caseCapsUkr: '3',
//       caseCapsShiftUkr: '№',
//       caseDownUkr: '3',
//       caseUpUkr: '№',
//     },
//     {
//       name: 'Digit4',
//       addClass: 'Digit4',
//       caseCapsEng: '4',
//       caseCapsShiftEng: '$',
//       caseDownEng: '4',
//       caseUpEng: '$',
//       caseCapsUkr: '4',
//       caseCapsShiftUkr: ';',
//       caseDownUkr: '4',
//       caseUpUkr: ';',
//     },
//     {
//       name: 'Digit5',
//       addClass: 'Digit5',
//       caseCapsEng: '5',
//       caseCapsShiftEng: '%',
//       caseDownEng: '5',
//       caseUpEng: '%',
//       caseCapsUkr: '5',
//       caseCapsShiftUkr: '%',
//       caseDownUkr: '5',
//       caseUpUkr: '%',
//     },
//     {
//       name: 'Digit6',
//       addClass: 'Digit6',
//       caseCapsEng: '6',
//       caseCapsShiftEng: '^',
//       caseDownEng: '6',
//       caseUpEng: '^',
//       caseCapsUkr: '6',
//       caseCapsShiftUkr: ':',
//       caseDownUkr: '6',
//       caseUpUkr: ':',
//     },
//     {
//       name: 'Digit7',
//       addClass: 'Digit7',
//       caseCapsEng: '7',
//       caseCapsShiftEng: '&',
//       caseDownEng: '7',
//       caseUpEng: '&',
//       caseCapsUkr: '7',
//       caseCapsShiftUkr: '?',
//       caseDownUkr: '7',
//       caseUpUkr: '?',
//     },
//     {
//       name: 'Digit8',
//       addClass: 'Digit8',
//       caseCapsEng: '8',
//       caseCapsShiftEng: '*',
//       caseDownEng: '8',
//       caseUpEng: '*',
//       caseCapsUkr: '8',
//       caseCapsShiftUkr: '*',
//       caseDownUkr: '8',
//       caseUpUkr: '*',
//     },
//     {
//       name: 'Digit9',
//       addClass: 'Digit9',
//       caseCapsEng: '9',
//       caseCapsShiftEng: '(',
//       caseDownEng: '9',
//       caseUpEng: '(',
//       caseCapsUkr: '9',
//       caseCapsShiftUkr: '(',
//       caseDownUkr: '9',
//       caseUpUkr: '(',
//     },
//     {
//       name: 'Digit0',
//       addClass: 'Digit0',
//       caseCapsEng: '0',
//       caseCapsShiftEng: ')',
//       caseDownEng: '0',
//       caseUpEng: ')',
//       caseCapsUkr: '0',
//       caseCapsShiftUkr: ')',
//       caseDownUkr: '0',
//       caseUpUkr: ')',
//     },
//     {
//       name: 'Minus',
//       addClass: 'Minus',
//       caseCapsEng: '-',
//       caseCapsShiftEng: '_',
//       caseDownEng: '-',
//       caseUpEng: '_',
//       caseCapsUkr: '-',
//       caseCapsShiftUkr: '_',
//       caseDownUkr: '-',
//       caseUpUkr: '_',
//     },
//     {
//       name: 'Equal',
//       addClass: 'Equal',
//       caseCapsEng: '=',
//       caseCapsShiftEng: '+',
//       caseDownEng: '=',
//       caseUpEng: '+',
//       caseCapsUkr: '=',
//       caseCapsShiftUkr: '+',
//       caseDownUkr: '=',
//       caseUpUkr: '+',
//     },
//     {
//       name: 'Backspace',
//       addClass: 'Backspace',
//       caseCapsEng: 'Backspace',
//       caseCapsShiftEng: 'Backspace',
//       caseDownEng: 'Backspace',
//       caseUpEng: 'Backspace',
//       caseCapsUkr: 'Backspace',
//       caseCapsShiftUkr: 'Backspace',
//       caseDownUkr: 'Backspace',
//       caseUpUkr: 'Backspace',
//     },
//   ],
//   [
//     {
//       name: 'Tab',
//       addClass: 'Tab',
//       caseCapsEng: 'Tab',
//       caseCapsShiftEng: 'Tab',
//       caseDownEng: 'Tab',
//       caseUpEng: 'Tab',
//       caseCapsUkr: 'Tab',
//       caseCapsShiftUkr: 'Tab',
//       caseDownUkr: 'Tab',
//       caseUpUkr: 'Tab',
//     },
//     {
//       name: 'KeyQ',
//       addClass: 'KeyQ',
//       caseCapsEng: 'q',
//       caseCapsShiftEng: 'Q',
//       caseDownEng: 'q',
//       caseUpEng: 'Q',
//       caseCapsUkr: 'й',
//       caseCapsShiftUkr: 'Й',
//       caseDownUkr: 'й',
//       caseUpUkr: 'Й',
//     },
//     {
//       name: 'KeyW',
//       addClass: 'KeyW',
//       caseCapsEng: 'w',
//       caseCapsShiftEng: 'W',
//       caseDownEng: 'w',
//       caseUpEng: 'W',
//       caseCapsUkr: 'ц',
//       caseCapsShiftUkr: 'Ц',
//       caseDownUkr: 'ц',
//       caseUpUkr: 'Ц',
//     },
//     {
//       name: 'KeyE',
//       addClass: 'KeyE',
//       caseCapsEng: 'e',
//       caseCapsShiftEng: 'E',
//       caseDownEng: 'e',
//       caseUpEng: 'E',
//       caseCapsUkr: 'у',
//       caseCapsShiftUkr: 'У',
//       caseDownUkr: 'у',
//       caseUpUkr: 'У',
//     },
//     {
//       name: 'KeyR',
//       addClass: 'KeyR',
//       caseCapsEng: 'r',
//       caseCapsShiftEng: 'R',
//       caseDownEng: 'r',
//       caseUpEng: 'R',
//       caseCapsUkr: 'к',
//       caseCapsShiftUkr: 'К',
//       caseDownUkr: 'к',
//       caseUpUkr: 'К',
//     },
//     {
//       name: 'KeyT',
//       addClass: 'KeyT',
//       caseCapsEng: 't',
//       caseCapsShiftEng: 'T',
//       caseDownEng: 't',
//       caseUpEng: 'T',
//       caseCapsUkr: 'е',
//       caseCapsShiftUkr: 'Е',
//       caseDownUkr: 'е',
//       caseUpUkr: 'Е',
//     },
//     {
//       name: 'KeyY',
//       addClass: 'KeyY',
//       caseCapsEng: 'y',
//       caseCapsShiftEng: 'Y',
//       caseDownEng: 'y',
//       caseUpEng: 'Y',
//       caseCapsUkr: 'н',
//       caseCapsShiftUkr: 'Н',
//       caseDownUkr: 'н',
//       caseUpUkr: 'Н',
//     },
//     {
//       name: 'KeyU',
//       addClass: 'KeyU',
//       caseCapsEng: 'u',
//       caseCapsShiftEng: 'U',
//       caseDownEng: 'u',
//       caseUpEng: 'U',
//       caseCapsUkr: 'г',
//       caseCapsShiftUkr: 'Г',
//       caseDownUkr: 'г',
//       caseUpUkr: 'Г',
//     },
//     {
//       name: 'KeyI',
//       addClass: 'KeyI',
//       caseCapsEng: 'i',
//       caseCapsShiftEng: 'I',
//       caseDownEng: 'i',
//       caseUpEng: 'I',
//       caseCapsUkr: 'ш',
//       caseCapsShiftUkr: 'Ш',
//       caseDownUkr: 'ш',
//       caseUpUkr: 'Ш',
//     },
//     {
//       name: 'KeyO',
//       addClass: 'KeyO',
//       caseCapsEng: 'o',
//       caseCapsShiftEng: 'O',
//       caseDownEng: 'o',
//       caseUpEng: 'O',
//       caseCapsUkr: 'щ',
//       caseCapsShiftUkr: 'Щ',
//       caseDownUkr: 'щ',
//       caseUpUkr: 'Щ',
//     },
//     {
//       name: 'KeyP',
//       addClass: 'KeyP',
//       caseCapsEng: 'p',
//       caseCapsShiftEng: 'P',
//       caseDownEng: 'p',
//       caseUpEng: 'P',
//       caseCapsUkr: 'з',
//       caseCapsShiftUkr: 'З',
//       caseDownUkr: 'з',
//       caseUpUkr: 'З',
//     },
//     {
//       name: 'BracketLeft',
//       addClass: 'BracketLeft',
//       caseCapsEng: '[',
//       caseCapsShiftEng: '{',
//       caseDownEng: '[',
//       caseUpEng: '{',
//       caseCapsUkr: 'х',
//       caseCapsShiftUkr: 'Х',
//       caseDownUkr: 'х',
//       caseUpUkr: 'Х',
//     },
//     {
//       name: 'BracketRight',
//       addClass: 'BracketRight',
//       caseCapsEng: ']',
//       caseCapsShiftEng: '}',
//       caseDownEng: ']',
//       caseUpEng: '}',
//       caseCapsUkr: 'ї',
//       caseCapsShiftUkr: 'Ї',
//       caseDownUkr: 'ї',
//       caseUpUkr: 'Ї',
//     },
//     {
//       name: 'Backslash',
//       addClass: 'Backslash',
//       caseCapsEng: '\\',
//       caseCapsShiftEng: '|',
//       caseDownEng: '\\',
//       caseUpEng: '|',
//       caseCapsUkr: '\\',
//       caseCapsShiftUkr: '/',
//       caseDownUkr: '\\',
//       caseUpUkr: '/',
//     },
//   ],
//   [
//     {
//       name: 'CapsLock',
//       addClass: 'CapsLock',
//       caseCapsEng: 'Caps Lock',
//       caseCapsShiftEng: 'Caps Lock',
//       caseDownEng: 'Caps Lock',
//       caseUpEng: 'Caps Lock',
//       caseCapsUkr: 'Caps Lock',
//       caseCapsShiftUkr: 'Caps Lock',
//       caseDownUkr: 'Caps Lock',
//       caseUpUkr: 'Caps Lock',
//     },
//     {
//       name: 'KeyA',
//       addClass: 'KeyA',
//       caseCapsEng: 'a',
//       caseCapsShiftEng: 'A',
//       caseDownEng: 'a',
//       caseUpEng: 'A',
//       caseCapsUkr: 'ф',
//       caseCapsShiftUkr: 'Ф',
//       caseDownUkr: 'ф',
//       caseUpUkr: 'Ф',
//     },
//     {
//       name: 'KeyS',
//       addClass: 'KeyS',
//       caseCapsEng: 's',
//       caseCapsShiftEng: 'S',
//       caseDownEng: 's',
//       caseUpEng: 'S',
//       caseCapsUkr: 'і',
//       caseCapsShiftUkr: 'І',
//       caseDownUkr: 'і',
//       caseUpUkr: 'І',
//     },
//     {
//       name: 'KeyD',
//       addClass: 'KeyD',
//       caseCapsEng: 'd',
//       caseCapsShiftEng: 'D',
//       caseDownEng: 'd',
//       caseUpEng: 'D',
//       caseCapsUkr: 'в',
//       caseCapsShiftUkr: 'В',
//       caseDownUkr: 'в',
//       caseUpUkr: 'В',
//     },
//     {
//       name: 'KeyF',
//       addClass: 'KeyF',
//       caseCapsEng: 'f',
//       caseCapsShiftEng: 'F',
//       caseDownEng: 'f',
//       caseUpEng: 'F',
//       caseCapsUkr: 'а',
//       caseCapsShiftUkr: 'А',
//       caseDownUkr: 'а',
//       caseUpUkr: 'А',
//     },
//     {
//       name: 'KeyG',
//       addClass: 'KeyG',
//       caseCapsEng: 'g',
//       caseCapsShiftEng: 'G',
//       caseDownEng: 'g',
//       caseUpEng: 'G',
//       caseCapsUkr: 'п',
//       caseCapsShiftUkr: 'П',
//       caseDownUkr: 'п',
//       caseUpUkr: 'П',
//     },
//     {
//       name: 'KeyH',
//       addClass: 'KeyH',
//       caseCapsEng: 'h',
//       caseCapsShiftEng: 'H',
//       caseDownEng: 'h',
//       caseUpEng: 'H',
//       caseCapsUkr: 'р',
//       caseCapsShiftUkr: 'Р',
//       caseDownUkr: 'р',
//       caseUpUkr: 'Р',
//     },
//     {
//       name: 'KeyJ',
//       addClass: 'KeyJ',
//       caseCapsEng: 'j',
//       caseCapsShiftEng: 'J',
//       caseDownEng: 'j',
//       caseUpEng: 'J',
//       caseCapsUkr: 'о',
//       caseCapsShiftUkr: 'О',
//       caseDownUkr: 'о',
//       caseUpUkr: 'О',
//     },
//     {
//       name: 'KeyK',
//       addClass: 'KeyK',
//       caseCapsEng: 'k',
//       caseCapsShiftEng: 'K',
//       caseDownEng: 'k',
//       caseUpEng: 'K',
//       caseCapsUkr: 'л',
//       caseCapsShiftUkr: 'Л',
//       caseDownUkr: 'л',
//       caseUpUkr: 'Л',
//     },
//     {
//       name: 'KeyL',
//       addClass: 'KeyL',
//       caseCapsEng: 'l',
//       caseCapsShiftEng: 'L',
//       caseDownEng: 'l',
//       caseUpEng: 'L',
//       caseCapsUkr: 'д',
//       caseCapsShiftUkr: 'Д',
//       caseDownUkr: 'д',
//       caseUpUkr: 'Д',
//     },
//     {
//       name: 'Semicolon',
//       addClass: 'Semicolon',
//       caseCapsEng: ';',
//       caseCapsShiftEng: ':',
//       caseDownEng: ';',
//       caseUpEng: ':',
//       caseCapsUkr: 'ж',
//       caseCapsShiftUkr: 'Ж',
//       caseDownUkr: 'ж',
//       caseUpUkr: 'Ж',
//     },
//     {
//       name: 'Quote',
//       addClass: 'Quote',
//       caseCapsEng: "'",
//       caseCapsShiftEng: '"',
//       caseDownEng: "'",
//       caseUpEng: '"',
//       caseCapsUkr: 'є',
//       caseCapsShiftUkr: 'Є',
//       caseDownUkr: 'є',
//       caseUpUkr: 'Є',
//     },
//     {
//       name: 'Enter',
//       addClass: 'Enter',
//       caseCapsEng: 'Enter',
//       caseCapsShiftEng: 'Enter',
//       caseDownEng: 'Enter',
//       caseUpEng: 'Enter',
//       caseCapsUkr: 'Enter',
//       caseCapsShiftUkr: 'Enter',
//       caseDownUkr: 'Enter',
//       caseUpUkr: 'Enter',
//     },
//   ],
//   [
//     {
//       name: 'Shift',
//       addClass: 'ShiftLeft',
//       caseCapsEng: 'Shift',
//       caseCapsShiftEng: 'Shift',
//       caseDownEng: 'Shift',
//       caseUpEng: 'Shift',
//       caseCapsUkr: 'Shift',
//       caseCapsShiftUkr: 'Shift',
//       caseDownUkr: 'Shift',
//       caseUpUkr: 'Shift',
//     },
//     {
//       name: 'KeyZ',
//       addClass: 'KeyZ',
//       caseCapsEng: 'z',
//       caseCapsShiftEng: 'Z',
//       caseDownEng: 'z',
//       caseUpEng: 'Z',
//       caseCapsUkr: 'я',
//       caseCapsShiftUkr: 'Я',
//       caseDownUkr: 'я',
//       caseUpUkr: 'Я',
//     },
//     {
//       name: 'KeyX',
//       addClass: 'KeyX',
//       caseCapsEng: 'x',
//       caseCapsShiftEng: 'X',
//       caseDownEng: 'x',
//       caseUpEng: 'X',
//       caseCapsUkr: 'ч',
//       caseCapsShiftUkr: 'Ч',
//       caseDownUkr: 'ч',
//       caseUpUkr: 'Ч',
//     },
//     {
//       name: 'KeyC',
//       addClass: 'KeyC',
//       caseCapsEng: 'c',
//       caseCapsShiftEng: 'C',
//       caseDownEng: 'c',
//       caseUpEng: 'C',
//       caseCapsUkr: 'c',
//       caseCapsShiftUkr: 'C',
//       caseDownUkr: 'c',
//       caseUpUkr: 'C',
//     },
//     {
//       name: 'KeyV',
//       addClass: 'KeyV',
//       caseCapsEng: 'v',
//       caseCapsShiftEng: 'V',
//       caseDownEng: 'v',
//       caseUpEng: 'V',
//       caseCapsUkr: 'м',
//       caseCapsShiftUkr: 'М',
//       caseDownUkr: 'м',
//       caseUpUkr: 'М',
//     },
//     {
//       name: 'KeyB',
//       addClass: 'KeyB',
//       caseCapsEng: 'b',
//       caseCapsShiftEng: 'B',
//       caseDownEng: 'b',
//       caseUpEng: 'B',
//       caseCapsUkr: 'и',
//       caseCapsShiftUkr: 'И',
//       caseDownUkr: 'и',
//       caseUpUkr: 'И',
//     },
//     {
//       name: 'KeyN',
//       addClass: 'KeyN',
//       caseCapsEng: 'n',
//       caseCapsShiftEng: 'N',
//       caseDownEng: 'n',
//       caseUpEng: 'N',
//       caseCapsUkr: 'т',
//       caseCapsShiftUkr: 'Т',
//       caseDownUkr: 'т',
//       caseUpUkr: 'Т',
//     },
//     {
//       name: 'KeyM',
//       addClass: 'KeyM',
//       caseCapsEng: 'm',
//       caseCapsShiftEng: 'M',
//       caseDownEng: 'm',
//       caseUpEng: 'M',
//       caseCapsUkr: 'Ь',
//       caseCapsShiftUkr: 'ь',
//       caseDownUkr: 'Ь',
//       caseUpUkr: 'ь',
//     },
//     {
//       name: 'Comma',
//       addClass: 'Comma',
//       caseCapsEng: ',',
//       caseCapsShiftEng: '<',
//       caseDownEng: ',',
//       caseUpEng: '<',
//       caseCapsUkr: 'б',
//       caseCapsShiftUkr: 'Б',
//       caseDownUkr: 'б',
//       caseUpUkr: 'Б',
//     },
//     {
//       name: 'Period',
//       addClass: 'Period',
//       caseCapsEng: '>',
//       caseCapsShiftEng: '.',
//       caseDownEng: '>',
//       caseUpEng: '.',
//       caseCapsUkr: 'ю',
//       caseCapsShiftUkr: 'Ю',
//       caseDownUkr: 'ю',
//       caseUpUkr: 'Ю',
//     },
//     {
//       name: 'Slash',
//       addClass: 'Slash',
//       caseCapsEng: '?',
//       caseCapsShiftEng: '/',
//       caseDownEng: '?',
//       caseUpEng: '/',
//       caseCapsUkr: ',',
//       caseCapsShiftUkr: '.',
//       caseDownUkr: ',',
//       caseUpUkr: '.',
//     },
//     {
//       name: 'ArrowUp',
//       addClass: 'ArrowUp',
//       caseCapsEng: '▲',
//       caseCapsShiftEng: '▲',
//       caseDownEng: '▲',
//       caseUpEng: '▲',
//       caseCapsUkr: '▲',
//       caseCapsShiftUkr: '▲',
//       caseDownUkr: '▲',
//       caseUpUkr: '▲',
//     },
//     {
//       name: 'Shift',
//       addClass: 'ShiftRight',
//       caseCapsEng: 'Shift',
//       caseCapsShiftEng: 'Shift',
//       caseDownEng: 'Shift',
//       caseUpEng: 'Shift',
//       caseCapsUkr: 'Shift',
//       caseCapsShiftUkr: 'Shift',
//       caseDownUkr: 'Shift',
//       caseUpUkr: 'Shift',
//     },
//   ],
//   [
//     {
//       name: 'Ctrl',
//       addClass: 'ControlLeft',
//       caseCapsEng: 'Ctrl',
//       caseCapsShiftEng: 'Ctrl',
//       caseDownEng: 'Ctrl',
//       caseUpEng: 'Ctrl',
//       caseCapsUkr: 'Ctrl',
//       caseCapsShiftUkr: 'Ctrl',
//       caseDownUkr: 'Ctrl',
//       caseUpUkr: 'Ctrl',
//     },
//     {
//       name: 'Function',
//       addClass: 'Function',
//       caseCapsEng: 'Fn',
//       caseCapsShiftEng: 'Fn',
//       caseDownEng: 'Fn',
//       caseUpEng: 'Fn',
//       caseCapsUkr: 'Fn',
//       caseCapsShiftUkr: 'Fn',
//       caseDownUkr: 'Fn',
//       caseUpUkr: 'Fn',
//     },
//     {
//       name: 'MetaLeft',
//       addClass: 'MetaLeft',
//       caseCapsEng: 'Win',
//       caseCapsShiftEng: 'Win',
//       caseDownEng: 'Win',
//       caseUpEng: 'Win',
//       caseCapsUkr: 'Win',
//       caseCapsShiftUkr: 'Win',
//       caseDownUkr: 'Win',
//       caseUpUkr: 'Win',
//     },
//     {
//       name: 'AltLeft',
//       addClass: 'AltLeft',
//       caseCapsEng: 'Alt',
//       caseCapsShiftEng: 'Alt',
//       caseDownEng: 'Alt',
//       caseUpEng: 'Alt',
//       caseCapsUkr: 'Alt',
//       caseCapsShiftUkr: 'Alt',
//       caseDownUkr: 'Alt',
//       caseUpUkr: 'Alt',
//     },
//     {
//       name: 'Space',
//       addClass: 'Space',
//       caseCapsEng: '',
//       caseCapsShiftEng: '',
//       caseDownEng: '',
//       caseUpEng: '',
//       caseCapsUkr: '',
//       caseCapsShiftUkr: '',
//       caseDownUkr: '',
//       caseUpUkr: '',
//     },
//     {
//       name: 'AltRight',
//       addClass: 'AltRight',
//       caseCapsEng: 'Alt',
//       caseCapsShiftEng: 'Alt',
//       caseDownEng: 'Alt',
//       caseUpEng: 'Alt',
//       caseCapsUkr: 'Alt',
//       caseCapsShiftUkr: 'Alt',
//       caseDownUkr: 'Alt',
//       caseUpUkr: 'Alt',
//     },
//     {
//       name: 'ArrowLeft',
//       addClass: 'ArrowLeft',
//       caseCapsEng: '◄',
//       caseCapsShiftEng: '◄',
//       caseDownEng: '◄',
//       caseUpEng: '◄',
//       caseCapsUkr: '◄',
//       caseCapsShiftUkr: '◄',
//       caseDownUkr: '◄',
//       caseUpUkr: '◄',
//     },
//     {
//       name: 'ArrowDown',
//       addClass: 'ArrowDown',
//       caseCapsEng: '▼',
//       caseCapsShiftEng: '▼',
//       caseDownEng: '▼',
//       caseUpEng: '▼',
//       caseCapsUkr: '▼',
//       caseCapsShiftUkr: '▼',
//       caseDownUkr: '▼',
//       caseUpUkr: '▼',
//     },
//     {
//       name: 'ArrowRight',
//       addClass: 'ArrowRight',
//       caseCapsEng: '►',
//       caseCapsShiftEng: '►',
//       caseDownEng: '►',
//       caseUpEng: '►',
//       caseCapsUkr: '►',
//       caseCapsShiftUkr: '►',
//       caseDownUkr: '►',
//       caseUpUkr: '►',
//     },
//     {
//       name: 'ControlRight',
//       addClass: 'ControlRight',
//       caseCapsEng: 'Ctrl',
//       caseCapsShiftEng: 'Ctrl',
//       caseDownEng: 'Ctrl',
//       caseUpEng: 'Ctrl',
//       caseCapsUkr: 'Ctrl',
//       caseCapsShiftUkr: 'Ctrl',
//       caseDownUkr: 'Ctrl',
//       caseUpUkr: 'Ctrl',
//     },
//   ],
// ];

const data = [
  [
    {
      class: ['Backquote', 'number'],
      eng: ['`', '~'],
      ukr: ["'", "₴"]
    },
    {
      class: ['Digit1', 'number'],
      eng: ['1', '!'],
      ukr: ['1', '!']
    },
    {
      class: ['Digit2', 'number'],
      eng: ['2', '@'],
      ukr: ['2', '"']
    },
    {
      class: ['Digit3', 'number'],
      eng: ['3', '#'],
      ukr: ['3', '№']
    },
    {
      class: ['Digit4', 'number'],
      eng: ['4', '$'],
      ukr: ['4', ';']
    },
    {
      class: ['Digit5', 'number'],
      eng: ['5', '%'],
      ukr: ['5', '%']
    },
    {
      class: ['Digit6', 'number'],
      eng: ['6', ':'],
      ukr: ['6', '^']
    },
    {
      class: ['Digit7', 'number'],
      eng: ['7', '?'],
      ukr: ['7', '&']
    },
    {
      class: ['Digit8', 'number'],
      eng: ['8', '*'],
      ukr: ['8', '*']
    },
    {
      class: ['Digit9', 'number'],
      eng: ['9', '('],
      ukr: ['9', '(']
    },
    {
      class: ['Digit0', 'number'],
      eng: ['0', ')'],
      ukr: ['0', ')']
    },
    {
      class: ['Minus', 'number'],
      eng: ['-', '_'],
      ukr: ['-', '_']
    },
    {
      class: ['Equal', 'number'],
      eng: ['=', '+'],
      ukr: ['=', '+']
    },
    {
      class: ['Backspace', 'special'],
      eng: ['Backspace'],
      ukr: ['Backspace']
    },
  ],
  [
    {
      class: ['Tab', 'special'],
      eng: ['Tab'],
      ukr: ["Tab"]
    },
    {
      class: ['KeyQ', 'character'],
      eng: ["q"],
      ukr: ["й"]
    },
    {
      class: ['KeyW', 'character'],
      eng: ["w"],
      ukr: ["ц"]
    },
    {
      class: ['KeyE', 'character'],
      eng: ["e"],
      ukr: ["у"]
    },
    {
      class: ['KeyR', 'character'],
      eng: ["r"],
      ukr: ["к"]
    },
    {
      class: ['KeyT', 'character'],
      eng: ["t"],
      ukr: ["е"]
    },
    {
      class: ['KeyY', 'character'],
      eng: ["y"],
      ukr: ["н"]
    },
    {
      class: ['KeyU', 'character'],
      eng: ["u"],
      ukr: ["г"]
    },
    {
      class: ['KeyI', 'character'],
      eng: ["i"],
      ukr: ["ш"]
    },
    {
      class: ['KeyO', 'character'],
      eng: ["o"],
      ukr: ["щ"]
    },
    {
      class: ['KeyP', 'character'],
      eng: ["p"],
      ukr: ["з"]
    },
    {
      class: ['BracketLeft', 'character'],
      eng: ["[", "{"],
      ukr: ["х"]
    },
    {
      class: ['BracketRight', 'character'],
      eng: ["]", "}"],
      ukr: ["ї"]
    },
    {
      class: ['Backslash', 'character'],
      eng: ["\\", "|"],
      ukr: ["\\", "/"]
    },
  ],
  [
    {
      class: ['CapsLock', 'special'],
      eng: ["Caps Lock"],
      ukr: ["Caps Lock"]
    },
    {
      class: ['KeyA', 'character'],
      eng: ["a"],
      ukr: ["ф"]
    },
    {
      class: ['KeyS', 'character'],
      eng: ["s"],
      ukr: ["і"]
    },
    {
      class: ['KeyD', 'character'],
      eng: ["d"],
      ukr: ["в"]
    },
    {
      class: ['KeyF', 'character'],
      eng: ["f"],
      ukr: ["а"]
    },
    {
      class: ['KeyG', 'character'],
      eng: ["g"],
      ukr: ["п"]
    },
    {
      class: ['KeyH', 'character'],
      eng: ["h"],
      ukr: ["р"]
    },
    {
      class: ['KeyJ', 'character'],
      eng: ["j"],
      ukr: ["о"]
    },
    {
      class: ['KeyK', 'character'],
      eng: ["k"],
      ukr: ["л"]
    },
    {
      class: ['KeyL', 'character'],
      eng: ["l"],
      ukr: ["д"]
    },
    {
      class: ['Semicolon', 'character'],
      eng: [";", ":"],
      ukr: ["ж"]
    },
    {
      class: ['Quote', 'character'],
      eng: [`'`, `"`],
      ukr: ["є"]
    },
    {
      class: ['Enter', 'special'],
      eng: [`Enter`],
      ukr: ["Enter"]
    },
  ],
  [
     {
      class: ['ShiftLeft', 'special'],
      eng: [`Shift`],
      ukr: ["Shift"]
    },
    {
      class: ['KeyZ', 'character'],
      eng: ["z"],
      ukr: ["я"]
    },
   {
      class: ['KeyX', 'character'],
      eng: ["x"],
      ukr: ["ч"]
    },
    {
      class: ['KeyC', 'character'],
      eng: ["c"],
      ukr: ["с"]
    },
    {
      class: ['KeyV', 'character'],
      eng: ["v"],
      ukr: ["м"]
    },
    {
      class: ['KeyB', 'character'],
      eng: ["b"],
      ukr: ["и"]
    },
    {
      class: ['KeyN', 'character'],
      eng: ["n"],
      ukr: ["т"]
    },
    {
      class: ['KeyM', 'character'],
      eng: ["m"],
      ukr: ["ь"]
    },
    {
      class: ['Comma', 'character'],
      eng: [",", "<"],
      ukr: ["б"]
    },
    {
      class: ['Period', 'character'],
      eng: [".", ">"],
      ukr: ["ю"]
    },
    {
      class: ['Slash', 'character'],
      eng: ["/", "?"],
      ukr: [".", ","]
    },
    {
      class: ['ArrowUp', 'special'],
      eng: ["▲"],
      ukr: ["▲"]
    },
    {
      class: ['ShiftRight', 'special'],
      eng: ["Shift"],
      ukr: ["Shift"]
    },
  ],
  [
    {
      class: ['ControlLeft', 'special'],
      eng: ["Ctrl"],
      ukr: ["Ctrl"]
    },
    {
      class: ['Function', 'special'],
      eng: ["Fn"],
      ukr: ["Fn"]
    },
    {
      class: ['MetaLeft', 'special'],
      eng: ["Win"],
      ukr: ["Win"]
    },
    {
      class: ['AltLeft', 'special'],
      eng: ["Alt"],
      ukr: ["Alt"]
    },
    {
      class: ['Space', 'special'],
      eng: [""],
      ukr: [""]
    },
    {
      class: ['AltRight', 'special'],
      eng: ["Alt"],
      ukr: ["Alt"]
    },
    {
      class: ['ArrowLeft', 'special'],
      eng: ["◄"],
      ukr: ["◄"]
    },
    {
      class: ['ArrowDown', 'special'],
      eng: ["▼"],
      ukr: ["▼"]
    },
    {
      class: ['ArrowRight', 'special'],
      eng: ["►"],
      ukr: ["►"]
    },
    {
      class: ['ControlRight', 'special'],
      eng: ["Ctrl"],
      ukr: ["Ctrl"]
    },
  ],
];

export default data;
